baseURL = "http://gavv.net/"
languageCode = "en-us"
title = "Victor Gaydov"

pluralizelisttitles = false
staticDir = ["site", "media", "redirects"]

disableKinds = ["taxonomy"]

[pagination]
  pageSize = 15

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.tableOfContents]
    endLevel = 1
    startLevel = 1

[Params]
  author = "Victor Gaydov"
