baseURL = "http://gavv.github.io/"
languageCode = "en-us"
title = "Victor Gaydov"

pluralizelisttitles = false
staticDir = ["site", "media", "redirects"]

disableKinds = ["taxonomyTerm"]

[taxonomies]
  tag = "tags"

[Params]
  author = "Victor Gaydov"
