baseURL = "http://gavv.net/"
languageCode = "en-us"
title = "Victor Gaydov"

pluralizelisttitles = false
staticDir = ["site", "media", "redirects"]

disableKinds = ["taxonomyTerm"]

paginate = 15

[taxonomies]
  tag = "tags"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[Params]
  author = "Victor Gaydov"
